### PR TITLE
Add deps for postgres, add mediainfo

### PR DESCRIPTION
**Pull request by thespad**
[linuxserverurl]: https://linuxserver.io
[linuxserver.io][linuxserverurl]

------------------------------

 - [x] I have read the [contributing](https://github.com/linuxserver/docker-bazarr/blob/master/.github/CONTRIBUTING.md) guideline and understand that I have made the correct modifications

------------------------------

## Description:
Closes https://github.com/linuxserver/docker-bazarr/issues/108
Closes https://github.com/morpheus65535/bazarr/issues/2063

### CODE REVIEW

**Review by Roxedus — APPROVED** [review]

**Comment by hlugt** [comment]
Yep, it connects to postgres. Seems to work without problems.
Thanks!

**Comment by hlugt** [comment]
Nice to have mediainfo as well btw!

**Comment by morpheus65535** [comment]
Hey gus, could we get the same in latest image please?

**Comment by thespad** [comment]
> Hey guys, could we get the same in latest image please?

https://github.com/linuxserver/docker-bazarr/pull/110

Note that we can't merge it until you merge the changes upstream because the postgres requirements file won't exist until then.

**Comment by morpheus65535** [comment]
Sorry about that, I should have drink one more coffee this morning ;-)

I'll get back to you once it's merged on my side.

**Comment by morpheus65535** [comment]
@thespad I've just merged it. The file is there, you can merge yours. Thanks!

**Comment by thespad** [comment]
> @thespad I've just merged it. The file is there, you can merge yours. Thanks!

Done.

**Comment by morpheus65535** [comment]
@thespad thanks mate!

@halali do you want to test it?

**Pull request merged**
